### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by MichielMostmans** [SUSE/hanadb_exporter#69]
We are implementing the hanadb_exporter on our infrastructure but noticed that the tool has quite a big impact on CPU usage on big HANA installations, mainly caused by some of the queries from the metrics.json (SELECT TOP 10 ct.host, LPAD(ct.port,5) port, ct.schema_name, ct.table_name...  is the heaviest one).

We could of course remove the heavy queries from the metrics.json, but would prefer to collect them at a much lower frequency.  Some data are quite stable and so there's no need to collect them so often.  We would install multiple hanadb_exporter instances: one with a metrics file for "light" queries that are collected often, and one with "heavy" queries that we only collect a few times a day.

Right now there doesn't seem to be a configuration option to set a collection interval. Would you consider to add such a feature?  I think other users can benefit from it because I can hardly image the current CPU impact is acceptable for most companies.

**Comment by diegoakechi** [comment]
@MichielMostmans ,

Thanks for the report. In our performance tests, we didn't identify any significant impact. Could you share how much was that in your case? And also, what kind of workload do you have running on your environment?

This split is something that we have discussed in the past and even have included in our backlog, but we still need some research on how to best implement that.

Basically, Prometheus follows a scrapping approach, which means that the Prometheus server is the one that determines the metrics collection interval and not the exporters. With that, on the current implementation, you could create two instances of the exporters on different ports both running a different set of queries.

On the Prometheus server you would need to create two different targets with different scrap intervals, similar to that:
```
 job_name: hana-monitor
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets:
         - {{ ip }}:9668

job_name: hana-heavy
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets:
         - {{ ip }}:9678
  ```

This should work, but it might be hard to compose a meaningful graph in Grafana with such long data collection intervals (daily for instance), as all the variations that might occur with different workloads executed during the day will probably not be presented, but you probably know your environment better than me =).
